### ISSUE TITLE
parallel NEURON does not launch properly with mpiexec

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#13]
Running:
```
jovyan@1303480783f6:~/nrn-7.4/src/parallel$ mpiexec -np 4 nrniv -mpi test0.hoc
```
Yields:
```
NEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
NEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits

NEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits

NEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits

Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits

Warning: detected user attempt to enable MPI, but MPI support was disabled at build time.
I am 0 of 1
Warning: detected user attempt to enable MPI, but MPI support was disabled at build time.
I am 0 of 1
Warning: detected user attempt to enable MPI, but MPI support was disabled at build time.
I am 0 of 1
Warning: detected user attempt to enable MPI, but MPI support was disabled at build time.
I am 0 of 1
```

**Comment by russelljjarvis** [comment]
So I have traced the bug back to a problem with 

./configure

The signal function does not need a cast for the handler
```
do SIGPOLL and I_GETSIG work: no
 But see config.log to see why it failed.
```
The config.log has the lines:
```
configure:21795: checking return type of signal handlers
configure:21813: gcc -c -g -O2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:58:1: error: void value not ignored as it ought to be
 return *(signal (0, 0)) (0) == 1;
 ^
```
and config.status on line 1342:
```
D["RETSIGTYPE"]=" void"
```
I have noticed also that a similar docker parallel neuron build is now generating the same non fatal error.

https://hub.docker.com/r/neuralensemble/simulation/~/dockerfile/

Also I believe you can start some parallel development regardless, as you can use the python module mpi4py to by pass a lot of the use cases of NEURONs `ParallelContext()`, as me about specific examples of this if you would like.

**Comment by russelljjarvis** [comment]
Okay I have created a hack solution, the code below gets you to the intended result. If you want to replicated it, create a new directory, copy and paste the contents of code block below into a file called Dockerfile.

Build it with something like:
```
sudo docker build -t pynet `pwd`
```
Run it with something like:
```
sudo docker run -it pynet

```
```
FROM neuralensemble/base
MAINTAINER andrew.davison@unic.cnrs-gif.fr
ENV NEST_VER=2.12.0 NRN_VER=7.4
ENV NEST=nest-simulator-$NEST_VER NRN=nrn-$NRN_VER
ENV PATH=$PATH:$VENV/bin
RUN ln -s /usr/bin/2to3-3.4 $VENV/bin/2to3
WORKDIR $HOME/packages
RUN wget http://www.neuron.yale.edu/ftp/neuron/versions/v$NRN_VER/$NRN.tar.gz
RUN tar xzf $NRN.tar.gz; rm $NRN.tar.gz

RUN mkdir $NRN; \
   cd $NRN; \
   $HOME/packages/$NRN/configure --with-paranrn --with-nrnpython=$VENV/bin/python --disable-rx3d --without-iv --prefix=$VENV; \
   make; make install; \
   cd src/nrnpython; $VENV/bin/python setup.py install; \
   cd $VENV/bin; ln -s ../x86_64/bin/nrnivmodl


WORKDIR /home/docker/
RUN echo "source $VENV/bin/activate" >> .bashrc
WORKDIR /home/docker/packages/nrn-7.4
RUN bash build.sh
RUN make
RUN make install

```
```
cd /home/docker/env/neurosci/x86_64/bin
(neurosci) docker@096cbed5baa3:~/env/neurosci/x86_64/bin$ mpiexec -np 4 ./nrniv -mpi ~/packages/nrn-7.4/src/parallel/test0.hoc 
numprocs=4
NEURON -- Release 7.4 (1370:16a7055d4a86) 2015-11-09
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2015
See http://www.neuron.yale.edu/neuron/credits

I am 1 of 4
I am 3 of 4
I am 0 of 4
I am 2 of 4
(neurosci) docker@096cbed5baa3:~/env/neurosci/x86_64/bin$ 
```

So obviously the neuronensemble base image, has a linux environment/configuration thats important to ours in some important way.

**Comment by russelljjarvis** [comment]
https://hub.docker.com/r/neuralensemble/base/~/dockerfile/

Differs from our build in two significant ways:
1 A whole heap of other packages:

I think its just the packages:  `libncurses5-dev libreadline-dev libgsl0-dev python3-mpi4py python3-tables cmake` 

That are the difference between a successful parallel build or not.
```

RUN apt-get update; apt-get install -y automake libtool build-essential openmpi-bin libopenmpi-dev git vim  \
                       wget python3 libpython3-dev libncurses5-dev libreadline-dev libgsl0-dev cython3 \
                       python3-pip python3-numpy python3-scipy python3-matplotlib python3-jinja2 python3-mock \
                       ipython3 python3-httplib2 python3-docutils python3-yaml \
                       python3-venv python3-mpi4py python3-tables cmake
```

**Comment by russelljjarvis** [comment]
Hi @rmhaynes 
Try git clone and docker run this:
https://github.com/russelljjarvis/ParallelPyNEURON/blob/master/Dockerfile

**Comment by rgerkin** [comment]
@russelljjarvis Can/Have you apply/applied these changes to our current Dockerfiles so that things work correctly?

**Comment by russelljjarvis** [comment]
As you have noted, I fixed this outside of docker stacks 6 days ago. However the fix requires a necessary departure from the ipython-notebook Debian base.

I observed that invocation of `nrniv` with `mpiexec` to work about 7 months ago when the repository above drew from an Ubuntu base (rather than Debian, it stopped working after using the docker-stacks Debian base), and it works again using `neuralensemble/simulation` base (actually just Ubuntu too).

I think there is some difference between the Debian base of docker-stacks and the neurodebiam base of `neuralensemble/simulation`, or any other ubuntu base that is making a critical difference in terms of being able to execute `mpiexec` and `nrniv` together or not.

This is a problem, as it means its easy to fix the problem outside of the hierarchical stack, but difficult to fix it, inside of it. Perhaps this does not matter, as its doubtful that someone would want to use nrniv and mpi with an ipython notebook. Technically its probably possible that do so using ipython-parallel with mpi as the backend set by ipcluster. 

Just in case, I recently checked from inside the perspective of the latest docker-stacks `docker-stacks/neuron-mpi-neuroml` build to see if anything has changed. The build still does not work using Debian, below is the Debian specific error that results from running: 

`/home/jovyan/nrn-7.4/src/parallel/mpiexec -np 5 nrniv -mpi test0.hoc`


```
  orte_plm_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[76ec936e4598:00030] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 128
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_set_name failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[76ec936e4598:00030] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file orterun.c at line 694
```

**Comment by russelljjarvis** [comment]
Actually is it okay if I just put the working [Dockerfile](https://github.com/russelljjarvis/ParallelPyNEURON/blob/master/Dockerfile)

inside the directory [neuron-mpi-neuroml](https://github.com/scidash/docker-stacks/tree/master/neuron-mpi-neuroml
)?

and then if necessary build other notebook functionality on top of it? 

In the event that someone did want to use jupyter notebook and ipcluster, ipyparallel with parallel neuron, I think its more viable to build this on top of Andrew Davisons base, and the Dockerfile cited in the top of this comment. 

I don't understand what the `neuralensemble/base` does differently, but investigating this issue is time consuming and not scientifically interesting.

**Comment by russelljjarvis** [comment]
I decided to just push the code that works, however I can't decipher what the critical difference actually is.

**Comment by rgerkin** [comment]
@russelljjarvis 
It's not really a stack if the images are not hierarchical, i.e. based on one another.  Also there is some guarantee (or I want there to be one) that someone could test any component of NeuronUnit from inside a notebook.  The neuronunit and neuronunit-showcase images are based on neuron-mpi-neuroml, therefore neuron-mpi-neuroml needs to based on scipy-notebook-plus.  

Since actually reconciling the two bases doesn't seem interesting, let's just keep two separate images, one based on the jupyter lineage and one on the neuralensemble one.  If you want to keep the neuron-mpi-neuroml name for the neuralensemble one, that's fine, but please create a new neuron-neuroml one (i.e. without mpi) that derives from scipy-notebook-plus.  This can just basically be the old Dockerfile before the changes you just made, assuming that one works (without mpi).

**Comment by russelljjarvis** [comment]
Yes it works without mpi just not with it. Also say if you wanted to use mpi with a notebook, thats kind of non trivial too although it is possible, you would need `ipcluster` and `ipyparallel`. I will look at it again tomorrow. I will collate and diff the collated files just to make sure I have not missed anything.

**Comment by rgerkin** [comment]
OK then I should be able to just go back one commit and use the Dockerfile that was there as the new neuron-neuroml Dockerfile.  I will then update the graph and the scripts.

**Comment by russelljjarvis** [comment]
Yes, thats fine. I think it makes sense to keep them separate, as the use cases are kind of separate as well.

**Comment by russelljjarvis** [comment]
Actually it bothered me a lot that it was not working, and I found the source of the problem.
All that I needed to do was do `apt-get install ssh` and now mpi works properly again, when the base is `FROM scidash/neuronunit`, I will see if I can get this to work using ipcluster and ipyparallel tomorrow.

**Comment by rgerkin** [comment]
That's great!  Thanks for looking into it.

**Comment by russelljjarvis** [comment]
AOK, its working okay again now with importing appropriately from docker-stacks hierarchy. Ip-cluster with mpi also works. 
https://github.com/scidash/docker-stacks/blob/master/neuron-mpi-neuroml/Dockerfile
The Dockerfile is a bit more ugly than I would like, there are lots of different things that can break compilation of NEURON-mpi so I will have to keep refining this same file in a piecemeal fashion.

**Comment by russelljjarvis** [comment]
I believe this issue is fixed now as the appropriate Dockerfile draws from `scidash/scipy-notebook-plus` in its `FROM` statement. Additionally the build passes parallel NEURON tests, and has some interoperabiliyt/compatibility with ipcluster/controller and ipython parallel. I can't exactly invoke h.ParallelContext() from ipython but that is due to a limitation of the `nrniv` invocation command: `mpiexec -n 4 nrniv -mpi -python /home/jovyan/nrn-7.4/src/parallel/test_fixed2.py`

I suspect ipythons functionality might be able to be achieved by importing ipythons modules into regular python. I believe that this current state offers more than status quo NEURON+Python+MPI however.

Something, I have not recently checked is do all of the paths work when you enter the container (as this is not always consistent with the paths working in the build of Dockerfile). I am finding they do not always work, but this is a different issue to the ones described above (and the desired programs will run, if they are called using the absolute path to the binary file that runs the program), so I will regard this particular issue as closed.
