### ISSUE TITLE
Request to add a small note to documentation

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#16]
If you do set `SCIDASH_HOME`, with something like: 
```
export SCIDASH_HOME="/home/user_name/git"
```
In the `~/.bashrc` or `~/.profile` file, then an addition step of navigating to Dockers graphical preferences and selecting the shared space is required to take effect, before it is possible to successfuly run the command, or equivalent commands:

```
bash shell neuron-mpi-neuroml -dev
```
docker: Error response from daemon: Mounts denied: sxfs/#namespaces for more info.
.
/sciunit and /home/user_name/git/neuronunit
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/
```

**Comment by rgerkin** [comment]
@russelljjarvis 
Is this only on Linux?  I didn't have this problem on my Mac.

**Comment by russelljjarvis** [comment]
Hi rick, no this is on Apple/Mac. Default docker install on Ubuntu native OS does not even have a GUI, or a GUI configuration. Its default is to give all access to all of the hosts resources.

Do you have the latest versions of Docker installed? Any way its not that important, it wouldn't have to be written up as directive, but just an aside note, that this might be necessary.
I see now that the above URL was broken I have fixed it above and below:
https://docs.docker.com/docker-for-mac/

**Comment by rgerkin** [comment]
Did you add this to the README for docker-stacks in one of the forks?

**Comment by rgerkin** [comment]
@russelljjarvis Did you do this?

**Comment by russelljjarvis** [comment]
No I had not done that. For some reason the issue went away. 

I believe the latest version of Docker on OSX does not require you to share directories through the GUI first.
