### ISSUE TITLE
second error:

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#20]
E: The method driver /usr/lib/apt/methods/https could not be found.
causing me to patch scidash/dockerstacks/neuronunit/Dockerfile by adding the last line:
```docker
RUN sudo apt-get install -y apt-transport-https
```

**Comment by rgerkin** [comment]
This is so deep I'd prefer to add this to scipy-notebook-plus.  Can you move it there?

**Comment by russelljjarvis** [comment]
Yes I have added it there. Testing the entire build process now with this change and the change from the other dockerbuild issue.
