### ISSUE TITLE
mpl.backend('Qt5Agg')

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#21]
When building with Ubuntu host OS, stack Debian target.

Python import of matplotlib seems to want:

```python
import matplotlib as mpl
mpl.backend('Qt5Agg')
```
Instead of old.

```python
import matplotlib as mpl
mpl.backend('Agg')
```
Hopefully this is some annoying thing that will go away without updating docker-stacks. Just posting here for information about error like:

could not connect to DISPLAY.

**Comment by rgerkin** [comment]
I think we have integrated this into most of the stacks.
