### ISSUE TITLE
In order for jNeuroML to work when it is invoked by pyNeuroML NEURON_HOME needs to be set.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#3]
In order for `jNeuroML` to work when it is invoked by `pyNeuroML` `NEURON_HOME` needs to be set, in the Dockerfile. 
The following line should be sufficient:
```RUN echo 'export NEURON_HOME=/home/jovyan/neuron/nrn-7.4/x86_64' >> ~/.bashrc```

**Comment by rgerkin** [comment]
Fixed I think in ca39d70, but leaving this open to confirm.

**Comment by russelljjarvis** [comment]
Work around found.
