### ISSUE TITLE
Force graceful rebuild of whole docker build dependency tree.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/docker-stacks#6]
Need to find appropriate docker build syntax that will force a graceful rebuild of whole docker build dependency tree. 

Current work around is to manually send rebuild commands for each dependency image.

If there are no detectable changes to Dockerfile, edit in nonsense `RUN echo` statements, which have no consequences for the build content, but do force rebuilding.

**Comment by rgerkin** [comment]
@russelljjarvis I saw a .yaml-based tool for configuring and running this, and I was going to use it, but then I started using Docker Cloud (this weekend), and you can actually have all that set up automatically.  I will show you this week.

**Comment by rgerkin** [comment]
In the meantime you can use something like the `build.sh` and `push.sh` scripts that I made in the dev branch.

**Comment by russelljjarvis** [comment]
Actually I feel like this script is helpful anyway, by poor habit I have given my images different names, which means I can't always just plug and play some of your code. By automating the naming of the images, it makes it easier to keep things consistent.

**Comment by rgerkin** [comment]
We can work on better naming conventions, and in the meantime you can just change the script to have both those names and any new names, and just have the script catch any non-existent names.  Or you could modify the script to discover the directories that contain a `Dockerfile`.  The only real requirement is that you try to have them ordered according to their dependency structure.
